// <auto-generated />
namespace Camarilla.RestApi.Infrastructure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateMailbox : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateMailbox));
        
        string IMigrationMetadata.Id
        {
            get { return "201601021329353_Mailbox"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
